### ISSUE TITLE
createProject MySQL failed to connect

### ISSUE THREAD

**Issue by derhecht** [bitnami/bitnami-docker-symfony#52]
**Description**

see steps to reproduce

could not create a symfony project with the commands from readme file

**Steps to reproduce the issue:**

1. fresh install include docker-compose up and validated browser call
2. run: docker-compose run myapp nami execute symfony createProject foo
3. results in: Starting application ...
symfony successfully initialized
mysql-c INFO  Trying to connect to MySQL server
Failed to connect to 127.0.0.1:3306 after 36 tries

**Describe the results you received:**

mysql-c INFO  Trying to connect to MySQL server
Failed to connect to 127.0.0.1:3306 after 36 tries

**Describe the results you expected:**

created project named foo

**Additional information you deem important (e.g. issue happens only occasionally):**

none

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 2
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: A5UW:IRV5:ZVEQ:YHLG:BQK2:HJLB:IEIG:ICV7:FZ3N:5QSY:6HEF:ONHM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 53
 System Time: 2017-04-28T15:41:09.258436369Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

using Mac OSX 10.12.4

**Comment by dbarranco** [comment]
Hi @derhecht 

Thank you so much for reporting that issue. 
I've been able to reproduce your issue and we will get that fixed in the next revision of the module. 

In the meantime you can apply this to get working your container:
* Open the `~/.nami/components/com.bitnami.symfony/nami.json` with your favourite text editor
* Now you must look for this parameter:
```
"databaseServerHost": {
          "default": "127.0.0.1"
        },
```
And replace `127.0.0.1` for `mariadb` (`mariadb` is the environment variable with the ip of the container of mariadb).

And that's it! now you should be able to execute the command  `docker-compose run myapp nami execute symfony createProject foo` from outside the container (inside the `myapp` folder). Furthermore, if you want to execute that command inside the container you can execute this:
`nami execute symfony createProject foo`.

This is the ouput I got after applying that fix:

```
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
symfony INFO  The Symfony project foo was created succesfully!
```

> Note: Take into account that before executing the command to create the project you should have the symfony container and the mariadb container running, this can be donde following the [ getting started section in the README file](https://github.com/bitnami/bitnami-docker-symfony#getting-started)

**Comment by robbygallo** [comment]
I have the same problem on linux, but i have not the folder `~/.nami/components/com.bitnami.symfony/nami.json`

dockercompose version
```
docker-compose version 1.17.0, build ac53b73
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
docker vesion
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by juan131** [comment]
Hello @robbygallo
 
Once you have your servers running (after running `docker-compose up`), you can obtain the Container ID by running: `docker ps`. After that, connect to the Symfony Container by running:

```
docker exec -it CONTAINER_ID bash
```

Once you're connected to the container, you'd find the **nami.json** file at `~/.nami/components/com.bitnami.symfony/nami.json`.
