### ISSUE TITLE
PHP 7.1 Upgrade

### ISSUE THREAD

**Issue by dextervip** [bitnami/bitnami-docker-symfony#58]
Hey,
It would great to upgrade PHP to 7.1 as some libraries are already requiring it. Latest doctrine/dbal requires  php: ^7.1

**Comment by andresbono** [comment]
Hi @dextervip, we will update all our PHP development containers to include PHP `7.1`. Thanks for the suggestion!

In the meantime, you may want to modify your Dockerfile to include php `7.1`. Change the following line from:

```
RUN bitnami-pkg install php-7.0.20-0 --checksum ...
```

to

```
RUN bitnami-pkg install php-7.1.7-0
```

Hope it helps!

**Comment by andresbono** [comment]
Hi @dextervip, we have just released a new revision of the container including PHP `7.1`. Find it here: [1.5.9-r1](https://github.com/bitnami/bitnami-docker-symfony/releases/tag/1.5.9-r1).
