### ISSUE TITLE
Upgrade to php 7.4

### ISSUE THREAD

**Issue by coolfarmer** [bitnami/bitnami-docker-symfony#66]
Is it possible to use your image with PHP 7.4 ?

Thanks!

**Comment by miguelaeh** [comment]
Hi @coolfarmer ,
We are currently working on release php 7.4 so we haven't tested our assets with php 7.4.

**Comment by miguelaeh** [comment]
Hi @coolfarmer ,
We recently released our image of PHP 7.4. We will be migrating the assets on the future to this version. If you take a look to the `Dockerfile`, Symphony is using `PHP 7.3`. You can test the `7.4` version changing the line:
```
RUN bitnami-pkg unpack php-7.3.13-0 --checksum 5e55d9741383f32ea8fadfbeae5a6fd9b86f188c67e9839e26449f80dd3addef
```
by 
```
RUN bitnami-pkg unpack php-7.4.0-0
```
Don't forget to remove the checksum.

In any case, have in mind we didn't test the assets with `PHP 7.4` yet, so it could be some unexpected issues.
I hope this will help you.
Regards.

**Comment by sameersbn** [comment]
putting the issue on hold until symfony is updated to php 7.4

**Comment by carrodher** [comment]
This issue was already solved
