### ISSUE TITLE
The volume sync speed it's way too slow (1 minute)

### ISSUE THREAD

**Issue by jmarcone** [bitnami/bitnami-docker-symfony#70]
**Description**
When using this docker image for developing the volume sync delay it's so slow that I can't work.
it takes over a minute for the container to reflect a change  in a file in my mounted folders.
For example in a controller return.

Does anyone have an idea why his could be happening?
I was very excited with the idea of having a proper docker image for developing my symfony apps, but this makes this image a no go

it doesn't happen with any other symfony docker configs I have running in my computer.

HD: I have an Samsung 860 EVO SATA III SSD, so 500MB/s.
OS: Ubuntu 18
image version: 1.5.11-debian-10-r109

**Steps to reproduce the issue:**

1. Install image
2. Add a controller and make changes

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 309
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-99-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.51GiB
 Name: jmarcone-Lenovo-ideapad-320-15IKB
 ID: MQRF:UG3I:GVI3:DB6Q:YBMW:N2IM:ZBW5:DHVR:AM2W:SMDI:56BU:J3FM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: iyyaz
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Comment by joancafom** [comment]
Hey @jmarcone !

Could you show me your `docker-compose.yml` file in case you did change anything from the original one? I launched the default configuration and created a simple [Controller](https://symfony.com/doc/current/page_creation.html#creating-a-page-route-and-controller) and the changes were instantly reflected. 

Also, from what I understood, you are doing something similar to what I did, right? (that is, installing a brand new container and performing changes on just a couple of files) 

Thanks!
