### ISSUE TITLE
Docker running Windows host - caching issues?

### ISSUE THREAD

**Issue by alex-barylski** [bitnami/bitnami-docker-symfony#71]
I am running this dockerfile on a Windows host (Docker for Windows) but Linux containerization...

Symfony works, but is very slow. I had similar issues with a vagrant/virtualbox. The fix was typically to move the cacheDir and logDir outside of the shared folder space:

https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-cache-directory

I have tried this with this container setup but I am still seeing very odd results, specifically the cache not clearing or the code changes not being applied, having to hit refresh multiple times or worse, having to:

`bin/console cache:clear`

This is very slow and quite frustrating. 

Have you had similar issues, or have any suggestions on what I might tweak?

**Comment by miguelaeh** [comment]
Hi @alex-barylski ,
I am not too familiar with that type of issues, but have you tried to disable the cache completely? In the following thread it is explained how to do it https://stackoverflow.com/questions/32397149/how-to-disable-cache-in-symfony/35477092
