### ISSUE TITLE
Symfony Version

### ISSUE THREAD

**Issue by MarcSN311** [bitnami/bitnami-docker-symfony#73]
Hello,
is there any way to see which symfony version this package provides?

**Comment by marcosbc** [comment]
Hi @MarcSN311, this Docker image includes Symfony Installer 1.5.11, meaning that each time you create a new project it will try to download the latest Symfony version by default via the [Symfony Skeleton](https://github.com/symfony/skeleton) Composer project (current version 5.2.99).

You can find the Symfony bootstrap logic in the `rootfs` folder: https://github.com/bitnami/bitnami-docker-symfony/blob/master/1/debian-10/rootfs/app-entrypoint.sh
