### ISSUE TITLE
Installing via pecl and enabling with docker-php-ext-enable crashes container

### ISSUE THREAD

**Issue by VeiJar1** [bitnami/bitnami-docker-symfony#75]
**Description**

Installing xdebug via PECL crashes container

**Steps to reproduce the issue:**

In your Dockerfile installing and trying to enable xdebug with 
RUN pecl install xdebug && docker-php-ext-enable xdebug 

**Describe the results you received:**
#6 18.64 /bin/sh: 1: docker-php-ext-enable: not found
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pecl install xdebug && docker-php-ext-enable xdebug]: exit code: 127

**Describe the results you expected:**

Xdebug would install and be enabled and container would not crash

**Comment by javsalgar** [comment]
Hi,

Could you let us know where you found the docker-php-ext-enable command? I don't recall this being part of the container.

**Comment by VeiJar1** [comment]
Hey, official PHP docker images use it to enable pecl modules. I tried to install xdebug via package manager but that doesn't work. Any idea how to get xdebug to work with this container?

**Comment by VeiJar1** [comment]
@javsalgar What is the reasoning for not using the official PHP docker images as base for this?

**Comment by javsalgar** [comment]
Hi,

I think it's an interesting feature. So far, we did not add it because it would require adding the build-essential packages, which could imply an increase in the container size. We have this example for adding extra modules, could you check it and see if it covers your use case? 

https://docs.bitnami.com/tutorials/create-custom-php-fpm-container-mongodb-support/

**Comment by VeiJar1** [comment]
Hey, I decided to make my own Docker-symfony base project with official PHP 8.0-fpm as base image for it. 
 But maybe I'll check it out some time!

**Comment by javsalgar** [comment]
Ok! If you check it again please let us know any feedback :)
