### ISSUE TITLE
executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by antoine-nedelec** [bitnami/bitnami-docker-symfony#76]
**Description**

Everything is up, can access the new app here: http://127.0.0.1:8000/
Can't execute symfony commands though docker explained as `docker-compose exec <service> <command>`

In my `docker-compose.yml`, my app service name is `test_app`.

I then tried:

-  `docker-compose exec test_app console doctrine:migrations:diff`
-  `docker-compose exec test_app bin/console doctrine:migrations:diff`
-  `docker-compose exec test_app symfony console doctrine:migrations:diff`
-  `docker-compose exec test_app symfony bin/console doctrine:migrations:diff`

but none works..

**Steps to reproduce the issue:**

1. docker compose up
2. Create entity
3. Try to migrate

**Comment by Mauraza** [comment]
Hi @antoine-nedelec,

Did you try this command `docker-compose exec test_app php bin/console doctrine:migrations:diff`?
