### ISSUE TITLE
Can't install easyAdmin / Problems with composer

### ISSUE THREAD

**Issue by tomwuell** [bitnami/bitnami-docker-symfony#78]
### Name and Version

Bitname/Symfony/version:6.0.6

### What steps will reproduce the bug?

Hey, 
I tried to install easyAdmin for Symphony. But the installation doesn't work because of some version issues concerning Symphony. Her ist the Bug-Report. What can I do to fix this Problem?

I used the command:"composer require admin" to try to install easyAdmin. 

Thanks for your support!

Best regards Tom 

### What is the expected behavior?

Installation von easyAdmin should work without Problems. 

### What do you see instead?

"Using version ^4.1 for easycorp/easyadmin-bundle
./composer.json has been updated
Running composer update easycorp/easyadmin-bundle
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.0.8"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires easycorp/easyadmin-bundle ^4.1 -> satisfiable by easycorp/easyadmin-bundle[v4.1.0, v4.1.1, v4.1.2].
    - easycorp/easyadmin-bundle[v4.1.0, ..., v4.1.2] require symfony/uid ^5.4|^6.0 -> found symfony/uid[v5.4.0, v5.4.2, v5.4.3, v6.0.0, v6.0.1, v6.0.2, v6.0.3] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require easycorp/easyadmin-bundle:*" to figure out if any version is installable, or "composer require easycorp/easyadmin-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

"

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-symfony#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
