### ISSUE TITLE
The dependencies in composer.json are messed up

### ISSUE THREAD

**Issue by threed-factory-store** [bitnami/bitnami-docker-symfony#79]
### Name and Version

bitnami/bitnami-docker-symfony:master

### What steps will reproduce the bug?

Install bitnami-docker-symfony
Run `composer update --with-all-dependencies`
You'll get tons of errors about conflicting requirements.

### What is the expected behavior?

Updates happen without a hitch

### What do you see instead?

Lots of hitches

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-symfony#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
